version: '3.9'

services:
  #NGINX
  jcrowe_wemod_web:
    image: nginx:latest
    ports:
      - '8282:80'
    volumes:
      - .:/var/www/html
      - ./docker/app/nginx/wemod.conf:/etc/nginx/conf.d/default.conf
    links:
      - jcrowe-wemod-php

  # App server
  jcrowe-wemod-php:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html
    links:
      - jcrowe-wemod-mysql
    working_dir: /var/www/html

  # MYSQL
  jcrowe-wemod-mysql:
    hostname: mysql
    image: mysql
    restart: always
    environment:
      MSYQL_DATABASE: 'wemod_project'
      MYSQL_USER: 'mysql_user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports: [ '33060:3306' ]
